### Auth Sign up
PUT http://localhost:3072/auth/signup
Content-Type: application/json

{
  "email": "gabrielsalomon.990@gmail.com",
  "name": "Gabriel",
  "password": "123456"
}


### Auth Verify Email
GET localhost:3072/auth/verify/8b1a0e26a6f0556e1df699aaa5ab8752170beeea7dc7d0885e958c247a48815e


### Auth Login 1
// -----------------------------------------------------------------------------------------------
POST http://localhost:3072/auth/login
Content-Type: application/json

{
    "email": "gabrielsalomon990@gmail.com",
    "password": "123456"
}

> {% client.global.set("authToken", response.body.token) %}


### Auth Login 2
// -----------------------------------------------------------------------------------------------
POST http://localhost:3072/auth/login
Content-Type: application/json

{
  "email": "admin2@test.com",
  "password": "admin"
}

> {% client.global.set("authToken", response.body.token) %}


### Auth Login 3
// -----------------------------------------------------------------------------------------------
POST http://localhost:3072/auth/login
Content-Type: application/json

{
  "email": "admin3@test.com",
  "password": "123456"
}

> {% client.global.set("authToken", response.body.token) %}
